# Generated by Django 2.0.2 on 2019-01-01 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='类型')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 22, 58, 42, 164279), verbose_name='日期')),
                ('money', models.IntegerField(default=0, null=True, verbose_name='金额(元)')),
                ('ps', models.CharField(max_length=32, verbose_name='备注')),
            ],
            options={
                'verbose_name': '账单信息',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
            },
        ),
        migrations.AddField(
            model_name='billinfo',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Classify'),
        ),
    ]
