# Generated by Django 2.0.2 on 2019-01-01 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinfo',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Classify', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 23, 8, 25, 770652), verbose_name='日期'),
        ),
    ]
